// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class ProductionFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCjjLLaI2aO5gUpKOtn9CNdLwBcREY42Y',
    appId: '1:828903241369:web:bb87fb4e04d597a9c96a08',
    messagingSenderId: '828903241369',
    projectId: 'pockeat-production',
    authDomain: 'pockeat-production.firebaseapp.com',
    storageBucket: 'pockeat-production.firebasestorage.app',
    measurementId: 'G-DTDRNQV1C7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0w_T19fAShx1FYZUVfBvkH3hAh1P_2U8',
    appId: '1:828903241369:android:043ea3c610d5421ac96a08',
    messagingSenderId: '828903241369',
    projectId: 'pockeat-production',
    storageBucket: 'pockeat-production.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMIPLV-urb8CSpTcnLaMaGIOyg5mOHoyc',
    appId: '1:828903241369:ios:6f8703bd8c0ea160c96a08',
    messagingSenderId: '828903241369',
    projectId: 'pockeat-production',
    storageBucket: 'pockeat-production.firebasestorage.app',
    iosClientId: '828903241369-le2l5aoatb0i7k6a8r3i8k2ilu22alne.apps.googleusercontent.com',
    iosBundleId: 'com.pockeat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMIPLV-urb8CSpTcnLaMaGIOyg5mOHoyc',
    appId: '1:828903241369:ios:c1aca9d400fb4416c96a08',
    messagingSenderId: '828903241369',
    projectId: 'pockeat-production',
    storageBucket: 'pockeat-production.firebasestorage.app',
    iosClientId: '828903241369-s1enu36rdrsdbrfu52ms2k7hjar8kogm.apps.googleusercontent.com',
    iosBundleId: 'com.example.amankendara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCjjLLaI2aO5gUpKOtn9CNdLwBcREY42Y',
    appId: '1:828903241369:web:0c2a452a753c7e3bc96a08',
    messagingSenderId: '828903241369',
    projectId: 'pockeat-production',
    authDomain: 'pockeat-production.firebaseapp.com',
    storageBucket: 'pockeat-production.firebasestorage.app',
    measurementId: 'G-CY1ZWTGD8H',
  );

}