// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class StagingFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPEgcGPfxodPANWZ14HsYWMFCpDgSdfFg',
    appId: '1:119378561262:web:8686d4c165ebeb2d324bff',
    messagingSenderId: '119378561262',
    projectId: 'pockeat-staging-f099c',
    authDomain: 'pockeat-staging-f099c.firebaseapp.com',
    storageBucket: 'pockeat-staging-f099c.firebasestorage.app',
    measurementId: 'G-72MKVR3912',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ5kjFArzJU_6WPe_PQW8v-V_TfJEKCII',
    appId: '1:119378561262:android:9d579c55db75a29f324bff',
    messagingSenderId: '119378561262',
    projectId: 'pockeat-staging-f099c',
    storageBucket: 'pockeat-staging-f099c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaHebBBdgYzUoFd5BPp6b8kGWtinWPNXc',
    appId: '1:119378561262:ios:843a9669cada44c1324bff',
    messagingSenderId: '119378561262',
    projectId: 'pockeat-staging-f099c',
    storageBucket: 'pockeat-staging-f099c.firebasestorage.app',
    iosClientId: '119378561262-snsh0bda6mvpam5m20ltncp6ujkctpil.apps.googleusercontent.com',
    iosBundleId: 'com.pockeat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaHebBBdgYzUoFd5BPp6b8kGWtinWPNXc',
    appId: '1:119378561262:ios:64816aecd2c59fe1324bff',
    messagingSenderId: '119378561262',
    projectId: 'pockeat-staging-f099c',
    storageBucket: 'pockeat-staging-f099c.firebasestorage.app',
    iosClientId: '119378561262-r8j2kq5gdte0p16nt403q928fs6ouj5p.apps.googleusercontent.com',
    iosBundleId: 'com.example.amankendara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPEgcGPfxodPANWZ14HsYWMFCpDgSdfFg',
    appId: '1:119378561262:web:26ba0ad31c48e830324bff',
    messagingSenderId: '119378561262',
    projectId: 'pockeat-staging-f099c',
    authDomain: 'pockeat-staging-f099c.firebaseapp.com',
    storageBucket: 'pockeat-staging-f099c.firebasestorage.app',
    measurementId: 'G-XRPLN4C84P',
  );
}
